apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qc5ap5h8k-nodejs
  janus-idp.io/tekton: qc5ap5h8k-nodejs
  backstage.io/kubernetes-id: qc5ap5h8k-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qc5ap5h8k-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
